### ISSUE TITLE
An error in limit maker code

### ISSUE THREAD

**Issue by andreypz** [ResonantHbbHgg/bbggLimits#20]
We get this error when running the bbggLTMaker code: 
```
Error in <TTree::Branch>: The class requested (vector<pair<double,float> >) for the branch "btmap" refer to an stl collection and do not have a compiled CollectionProxy.  Please generate the dictionary for this class (vector<pair<double,float> >)
```

I tried to fix it with Linkdef files but could not.
Even though the code works despite this error, I have a suspicion it may affect the results.

**Comment by rateixei** [comment]
It doesn't affect any result. It's just not saving the full set of b-tagging weights for all operating points of the signal jets in the limit tree (https://github.com/ResonantHbbHgg/bbggLimits/blob/master/src/bbggLTMaker.cc#L61 ). This branch is not used anywhere else in the analysis, at least until ICHEP 2017, I only used it to debug very briefly and didn't use it anymore :)

**Comment by andreypz** [comment]
Hi Rafael,

The original problem I'm trying to understand is the following:
* I take the script *ForApproval_MakeResonantAnalysis.py*, and run it for HighMasses = ['500', '550'] and resTypes = ['BulkGraviton']
   * The limits I obtain are the same as you get. Good.
* Now, I change bbggLTMaker code, like this:
https://github.com/ResonantHbbHgg/bbggLimits/blob/4a22d04c878598a920ec77551d8d2a8cf136cb28/src/bbggLTMaker.cc#L221-L226
This is a simple change that should not affect any results for the Resonant case.
However, for the above two masses it does change the result (slightly). I do not understand how... So my guess was some unrelated thing, like a memory leak of sorts. That's why I was trying to fix that error.
   * I don't understand why you say *btmap* is not used. Isn't it used to get b-tag scale factors? https://github.com/ResonantHbbHgg/bbggLimits/blob/d6eec0df5a2031b0ec8e836720906f9aa0543ee8/src/bbggLTMaker.cc#L244-L284
Or, perhaps you mean it is not needed to be saved in the limit tree?

**Comment by rateixei** [comment]
Hi, Andrey,

With respect to changing the limits, that's strange. Indeed it should not be different. Are you sure the event content on both limit trees are the same? Maybe a rounding error?

With respect to btmap, (1) it's not used at all in the results since it stores the cut-based b-tagging scale factors, while for the results, we used the differential method. (2) it's correctly used, it's just not correctly stored in the limit trees, which, indeed as you said, it does not need to be saved.

**Comment by andreypz** [comment]
Yes, it is strange. I don't think it's a rounding error, it's stranger than that. I will make another issue once I have more info.
I'm not sure if the content of the LT is the same, due to issue #21, which makes it harder to compare. Although the total number of events seem to be the same.

With respect to btmap - OK. I can comment it out and it does not effect anything. So, this is not an issue I suppose. So, I close this one.

**Comment by rateixei** [comment]
Thinking about it a bit more, it came to my mind that there might be a small extra difference due to this:
https://github.com/ResonantHbbHgg/bbggLimits/blob/d6eec0df5a2031b0ec8e836720906f9aa0543ee8/src/bbggLTMaker.cc#L331
This should only affect (and very little) the resonance masses close to the low mass/high mass threshold.

**Comment by andreypz** [comment]
Wait a second. Isn't it only for Non-resonant?
I think this part is involved instead for the Resonant:
https://github.com/ResonantHbbHgg/bbggLimits/blob/d6eec0df5a2031b0ec8e836720906f9aa0543ee8/src/bbggLTMaker.cc#L321

**Comment by rateixei** [comment]
No, for the final version of the analysis, both resonant and non-resonant results used the MVA based categorization.
https://github.com/ResonantHbbHgg/bbggLimits/blob/master/SmartScripts/ForApproval_MakeResonantAnalysis.py#L60

**Comment by andreypz** [comment]
Yes, indeed.
Actually, this is good news, because it makes sense now to me:)
